version: "3.7"
services:
  app:
    build:
      args:
        user: shashank
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: client-crud-assessment-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - local
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - local
networks:
  local:
    driver: bridge